// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    Overview: typeof import('./components/Overview.vue')['default']
    Ranking: typeof import('./components/Ranking.vue')['default']
    README: typeof import('./components/README.md')['default']
    Result: typeof import('./components/Result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./components/Setting.vue')['default']
    User: typeof import('./components/User.vue')['default']
  }
}

export {}
